### ISSUE TITLE
Fails to update wallpaper

### ISSUE THREAD

**Issue by z0rc** [dahlia/muzei-pixiv#11]
It's that time time of the year again.

Seems Pixiv caused this again.

**Comment by d3m3vilurr** [comment]
@z0rc thx for report. and fixed issue & released new [apk][1]. but f-droid deactivated auto update mode, so i made [mr][2] for this.
if merged that, i guess they will rebuild for the f-droid releases.

[1]: https://github.com/dahlia/muzei-pixiv/releases/tag/1.1.2
[2]: https://gitlab.com/fdroid/fdroiddata/merge_requests/2196
