### ISSUE TITLE
Stopped working, again

### ISSUE THREAD

**Issue by dogtopus** [dahlia/muzei-pixiv#17]
I haven't received any updates on wallpaper for months now

**Comment by d3m3vilurr** [comment]
@dogtopus @panyuhang93 sorry late fixes. I was too busy.

**Comment by panyuhang93** [comment]
Thank you very much!

**Comment by dogtopus** [comment]
Just tested the new release. The update can now be detected, but the wallpaper cannot be displayed correctly (always shows a black screen with a retry button)

**Comment by d3m3vilurr** [comment]
@dogtopus weird. in my phone work well. can you share your preference settings?

**Comment by dogtopus** [comment]
I found the problem: I didn't give muzei storage permission after I reinstalled it sometimes earlier. By giving it the correct permission everything works well now.
