### ISSUE TITLE
Stopped updating

### ISSUE THREAD

**Issue by z0rc** [dahlia/muzei-pixiv#6]
The app stopped updating wallpaper recently. Probably due to changes on the Pixiv side, though I cannot say for sure.

Also at this situation, when this app fails to retrieve the wallpaper it actively drains battery. Pixiv for Muzei actually showed up in battery stats with 7% drain. There is massive amount of PixivArtSource wakelocks.

**Comment by disjukr** [comment]
+1
i have this problem too

**Comment by d3m3vilurr** [comment]
This issue already fixed. #7
so, try install [this apk](https://bitbucket.org/d3m3vilurr/muzei-pixiv/downloads/muzei-pixiv-debug.apk)
If raise install error, remove old package. (this apk is not signed).

**Comment by z0rc** [comment]
@d3m3vilurr thank you very much for this!

Maybe you can publish this app within F-Droid repository? Pixiv called @dahlia C&D about Play Store published app, so she decided to abandon it. I recently had chat with her and it's OK to take the code and do whatever you like with it.

**Comment by z0rc** [comment]
@d3m3vilurr seems like it stopped updating again due to changes on the pixiv side. Any chance you can take a look?

**Comment by d3m3vilurr** [comment]
@z0rc few minute ago, I find new json api. :)

**Comment by z0rc** [comment]
@d3m3vilurr could you provide a built APK again? This would be much appreciated.

**Comment by d3m3vilurr** [comment]
@z0rc just wait few hour. (I'm little busy now, sorry).  I contacted dahlia, he gave to me maintaining permission. :-)
anyway, you need remove old package before install, new apk will change sign key.

**Comment by d3m3vilurr** [comment]
@z0rc yesterday taged [1.1.0](https://github.com/dahlia/muzei-pixiv/releases/tag/1.1.0). and published to [f-droid](https://f-droid.org/repository/browse/?fdfilter=muzei&fdid=com.pixiv.muzei.pixivsource).

**Comment by z0rc** [comment]
@d3m3vilurr you just made my day. Thanks!
